### ISSUE TITLE
Light switching off when display locked

### ISSUE THREAD

**Issue by vomikan** [Andrano/Light#1]
Hi there.

Could you please fix this issue.
After app start I close my phone (Samsung Galaxy A300) cover. A screen immediately locked and Light stopped as well.
But if a light switched on by a widget - it working after the cover closed or power button pressed. And I like it.

Also to protect battery and led lamp it reasonable to make short interrupts after 1, 2, 5 or 10 min of usage to indicate user: "I still needed?".

One more option may be usefull: use screen as lamp if a buttom on screem has toched. 

Regards,
Nikolay

**Comment by Andr3as** [comment]
Your additional enhancement to use screen as lamp is on my list.

The second one, to make short interrupts, is unnecessary in my opionion. It bothers the user. The user should be smart enough to know his needs (light vs. battery life).

**Comment by vomikan** [comment]
Hi,

Thank you for reply and fix.
You right that the user should be smart enough. But I think it will be nice
to care about a battery. Should be some smart options like child protection
or a phone in a pocket.

Regards,
Nikolay

2015-11-02 16:53 GMT+06:00 Andr3as notifications@github.com:
